version: "3.3"
services:
  ws:
    container_name: ws_server
    restart: on-failure
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"

  react-app:
    container_name: react_app
    restart: on-failure
    links:
      - "ws"
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ws